name: culinary-chronicler
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - python-dotenv
    - llama-index
    - llama-parse
    - chromadb
    - nest-asyncio
    - ollama
    - jupyter
    - llama-index-llms-ollama
    - llama_index.embeddings.huggingface
    - llama-index-vector-stores-chroma
